# Generated by Django 4.1.7 on 2023-02-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('klngTrackID', models.IntegerField(primary_key=True, serialize=False)),
                ('strTrackTitle', models.CharField(max_length=255)),
                ('strArtist', models.CharField(max_length=255)),
                ('strAlbum', models.CharField(max_length=255)),
                ('strRefTrCIMEB', models.CharField(max_length=255)),
                ('datTrackLength', models.DateTimeField()),
                ('strFile', models.CharField(max_length=255)),
                ('ysnVinyl', models.BooleanField()),
            ],
            options={
                'db_table': 'tblTracks',
            },
        ),
    ]
