# Generated by Django 4.1.7 on 2023-02-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_collcls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='datTrackLength',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='strAlbum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='strArtist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
