# Generated by Django 4.1.7 on 2023-02-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_collcls', '0003_alter_tracks_strfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='datTrackLength',
        ),
        migrations.AddField(
            model_name='tracks',
            name='durTrackLength',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
