# Generated by Django 4.1.7 on 2023-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_collcls', '0004_remove_tracks_dattracklength_tracks_durtracklength'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('klngExerciseID', models.IntegerField(primary_key=True, serialize=False)),
                ('strRefExCIMEB', models.CharField(max_length=20, null=True)),
                ('strExerciseEN', models.CharField(max_length=255, null=True)),
                ('memDescriptionEN', models.TextField(null=True)),
                ('ysnFilterOn', models.BooleanField(null=True)),
                ('strExerciseTypeID', models.CharField(max_length=20, null=True)),
                ('ysnLineV', models.BooleanField(null=True)),
                ('ysnLineS', models.BooleanField(null=True)),
                ('ysnLineC', models.BooleanField(null=True)),
                ('ysnLineA', models.BooleanField(null=True)),
                ('ysnLineT', models.BooleanField(null=True)),
            ],
        ),
    ]
