# Generated by Django 4.1.7 on 2023-02-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_collcls', '0005_exercise'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercise',
            table='Exercises',
        ),
        migrations.AlterModelTable(
            name='tracks',
            table='Tracks',
        ),
    ]
