# Generated by Django 4.1.7 on 2023-02-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_collcls', '0006_alter_exercise_table_alter_tracks_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='Exercises',
        ),
    ]
