# Generated by Django 4.1.7 on 2023-02-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_collcls', '0007_rename_exercise_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strRefExCIMEB', models.CharField(max_length=20, null=True)),
                ('strRefTrCIMEB', models.CharField(max_length=20, null=True)),
                ('strVersRefExTrCIMEB', models.CharField(max_length=5, null=True)),
                ('ysnFavorite', models.BooleanField(null=True)),
                ('memUserComment', models.TextField(null=True)),
                ('ysnLineV', models.BooleanField(null=True)),
                ('ysnLineS', models.BooleanField(null=True)),
                ('ysnLineC', models.BooleanField(null=True)),
                ('ysnLineA', models.BooleanField(null=True)),
                ('ysnLineT', models.BooleanField(null=True)),
                ('ysnAt1', models.BooleanField(null=True)),
                ('ysnAt2', models.BooleanField(null=True)),
                ('ysnAt3', models.BooleanField(null=True)),
                ('ysnAt5', models.BooleanField(null=True)),
                ('ysnAtG', models.BooleanField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_collcls.exercises')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_collcls.tracks')),
            ],
            options={
                'db_table': 'ExercisesTracks',
            },
        ),
    ]
