# Generated by Django 4.1.7 on 2023-02-26 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_collcls', '0008_exercisetrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('klngSessionID', models.IntegerField(primary_key=True, serialize=False)),
                ('strSessionName', models.CharField(max_length=255, null=True)),
                ('strSessionDate', models.DateTimeField(null=True)),
                ('strSessionLocation', models.CharField(max_length=255, null=True)),
                ('memSessionDescription', models.TextField(null=True)),
                ('strSessionType', models.CharField(choices=[('class', 'Class'), ('workshop', 'Workshop')], max_length=255, null=True)),
                ('ysnFavorite', models.BooleanField(null=True)),
                ('strAuthor', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(null=True)),
                ('memUserComment', models.TextField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_collcls.exercises')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_collcls.session')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_collcls.tracks')),
            ],
            options={
                'db_table': 'SessionTracks',
            },
        ),
    ]
