# Generated by Django 4.1.7 on 2023-02-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_collcls', '0009_session_sessiontrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('klngPlaylistID', models.IntegerField(primary_key=True, serialize=False)),
                ('strPlaylistName', models.CharField(max_length=255, null=True)),
                ('strPlaylistDate', models.DateTimeField(null=True)),
                ('strPlaylistLocation', models.CharField(max_length=255, null=True)),
                ('memPlaylistDescription', models.TextField(null=True)),
                ('strPlaylistType', models.CharField(choices=[('class', 'Class'), ('workshop', 'Workshop')], max_length=255, null=True)),
                ('ysnFavorite', models.BooleanField(null=True)),
                ('strAuthor', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Playlists',
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(null=True)),
                ('memUserComment', models.TextField(null=True)),
                ('Playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_collcls.playlist')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_collcls.exercises')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_collcls.tracks')),
            ],
            options={
                'db_table': 'PlaylistTracks',
            },
        ),
        migrations.RemoveField(
            model_name='sessiontrack',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='sessiontrack',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sessiontrack',
            name='track',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='SessionTrack',
        ),
    ]
