# Generated by Django 4.1.7 on 2023-03-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_collcls', '0010_playlist_playlisttrack_remove_sessiontrack_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlisttrack',
            name='Playlist',
        ),
        migrations.RemoveField(
            model_name='playlisttrack',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='playlisttrack',
            name='track',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistTrack',
        ),
    ]
