# Generated by Django 4.1.7 on 2023-03-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music_collcls', '0011_remove_playlisttrack_playlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('klngPlaylistID', models.AutoField(primary_key=True, serialize=False)),
                ('strPlaylistName', models.CharField(max_length=255, null=True, verbose_name='Playlist Name')),
                ('strPlaylistDate', models.DateTimeField(null=True, verbose_name='Playlist Date')),
                ('strPlaylistLocation', models.CharField(max_length=255, null=True, verbose_name='Playlist Location')),
                ('memPlaylistDescription', models.TextField(null=True, verbose_name='Playlist Description')),
                ('strPlaylistType', models.CharField(choices=[('class', 'Class'), ('workshop', 'Workshop')], max_length=255, null=True, verbose_name='Playlist Type')),
                ('ysnFavorite', models.BooleanField(null=True, verbose_name='Favorite')),
                ('strAuthor', models.CharField(max_length=255, null=True, verbose_name='Author')),
            ],
            options={
                'db_table': 'Playlists',
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(null=True)),
                ('memUserComment', models.TextField(null=True)),
                ('Playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_collcls.exercises')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_collcls.tracks')),
            ],
            options={
                'db_table': 'PlaylistTracks',
            },
        ),
    ]
